package org.sepses.rdf;/* CVS $Id: $ */

import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

/**
 * @author Auto-generated by schemagen on 18 May 2020 14:18
 */
public class LOG {
    /**
     * <p>The namespace of the vocabulary as a string</p>
     */
    public static final String NS = "https://w3id.org/sepses/ns/log#";
    public static final String NS_PREFIX = "log";
    public static final String NS_INSTANCE = "https://w3id.org/sepses/id/log/";
    public static final String NS_INSTANCE_PREFIX = "lid";
    /**
     * <p>The RDF model that holds the vocabulary terms</p>
     */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    /**
     * <p>The namespace of the vocabulary as a resource</p>
     */
    public static final Resource NAMESPACE = M_MODEL.createResource(NS);
    public static final Property address_host = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#address.host");
    public static final Property address_ipv4 = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#address.ipv4");
    public static final Property address_ipv6 = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#address.ipv6");
    public static final Property address_port = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#address.port");
    public static final Property app_name = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#app.name");
    public static final Property app_vend = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#app.vend");
    public static final Property app_ver = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#app.ver");
    public static final Property appname = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#appname");
    public static final Property cmd = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#cmd");
    public static final Property file_hashmd5 = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#file.hashmd5");
    public static final Property file_line = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#file.line");
    public static final Property file_mode = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#file.mode");
    public static final Property file_name = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#file.name");
    public static final Property file_path = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#file.path");
    public static final Property file_perm = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#file.perm");
    public static final Property file_size = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#file.size");
    public static final Property hasActionTag = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasActionTag");
    /**
     * <p>A relation between an Event and a Network Address (a combination of CEE:host,
     * CEE:ipv4, CEE:ipv6, an CEE:port)</p>
     */
    public static final Property hasAddress = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasAddress");
    /**
     * <p>Relation between an Event and an Application that it contained (CEE:app)</p>
     */
    public static final Property hasApp = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasApp");
    public static final Property hasDomainTag = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasDomainTag");
    /**
     * <p>Relation between an Event and its source address (CEE:host, CEE:ipv4, and
     * CEE:ipv6)</p>
     */
    public static final Property hasEventSource =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasEventSource");
    /**
     * <p>Relation between an Event and the Application that generated the event (a
     * combination of CEE:appname, CEE:vend, CEE:ver)</p>
     */
    public static final Property hasEventSourceApp =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasEventSourceApp");
    /**
     * <p>Relation between an Event and the Process that generated the event (a combination
     * of CEE:pname, CEE:pid, CEE:tid)</p>
     */
    public static final Property hasEventSourceProc =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasEventSourceProc");
    /**
     * <p>Generic relation between an Event and its annotations (Tag)</p>
     */
    public static final Property hasEventTag = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasEventTag");
    /**
     * <p>Relation between an Event and a File that it contained (CEE:file)</p>
     */
    public static final Property hasFile = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasFile");
    public static final Property hasFormat = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasFormat");
    /**
     * <p>A relation between Event and Host (in case there is an (incomplete) address
     * information - where there is no clear relation between Host, IP, and Port
     * available)</p>
     */
    public static final Property hasHost = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasHost");
    /**
     * <p>A relation between Event and IP (in case there is an (incomplete) address
     * information - where there is no clear relation between Host, IP, and Port
     * available)</p>
     */
    public static final Property hasIP = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasIP");
    /**
     * <p>A relation between Event and IPv4 (in case there is an (incomplete) address
     * information - where there is no clear relation between Host, IP, and Port
     * available)</p>
     */
    public static final Property hasIPv4 = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasIPv4");
    /**
     * <p>A relation between Event and IPv6 (in case there is an (incomplete) address
     * information - where there is no clear relation between Host, IP, and Port
     * available)</p>
     */
    public static final Property hasIPv6 = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasIPv6");
    /**
     * <p>Links between and Event and its Network destination (CEE:dst)</p>
     */
    public static final Property hasNetworkDestination =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasNetworkDestination");
    /**
     * <p>Links between and Event and its Network source (CEE:src)</p>
     */
    public static final Property hasNetworkSource =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasNetworkSource");
    public static final Property hasObjectTag = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasObjectTag");
    /**
     * <p>Relation between an Event and Field Objects</p>
     */
    public static final Property hasParameter = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasParameter");
    /**
     * <p>A relation between Event and Port (in case there is an (incomplete) address
     * information - where there is no clear relation between Host, IP, and Port
     * available)</p>
     */
    public static final Property hasPort = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasPort");
    /**
     * <p>Relation between an Event and a Process (CEE:proc)</p>
     */
    public static final Property hasProc = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasProc");
    public static final Property hasServiceTag =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasServiceTag");
    public static final Property hasSourceType =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasSourceType");
    public static final Property hasStatusTag = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasStatusTag");
    public static final Property hasSubjectTag =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasSubjectTag");
    /**
     * <p>Relation between an Event and its Syslog information (CEE:syslog)</p>
     */
    public static final Property hasSyslog = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasSyslog");
    public static final Property hasURL = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasURL");
    /**
     * <p>Relation between an Event and a User account that in contained (CEE:user)</p>
     */
    public static final Property hasUser = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#hasUser");
    public static final Property msg = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#msg");
    public static final Property originatedDevice =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#originatedDevice");
    public static final Property originatedLogSource =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#originatedLogSource");
    public static final Property parameter = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#parameter");
    public static final Property parameter_address =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#parameter.address");
    public static final Property parameter_app =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#parameter.app");
    public static final Property parameter_file =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#parameter.file");
    public static final Property parameter_proc =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#parameter.proc");
    public static final Property parameter_syslog =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#parameter.syslog");
    public static final Property parameter_user =
            M_MODEL.createProperty("https://w3id.org/sepses/ns/log#parameter.user");
    public static final Property pid = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#pid");
    public static final Property pname = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#pname");
    public static final Property proc_id = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#proc.id");
    public static final Property proc_name = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#proc.name");
    public static final Property proc_tid = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#proc.tid");
    public static final Property syslog_fac = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#syslog.fac");
    public static final Property syslog_pri = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#syslog.pri");
    public static final Property syslog_tag = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#syslog.tag");
    public static final Property syslog_ver = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#syslog.ver");
    public static final Property time = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#time");
    public static final Property uid = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#uid");
    public static final Property user_domain = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#user.domain");
    public static final Property user_gid = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#user.gid");
    public static final Property user_group = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#user.group");
    public static final Property user_id = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#user.id");
    public static final Property user_name = M_MODEL.createProperty("https://w3id.org/sepses/ns/log#user.name");
    /**
     * <p>The primary type of action that was undertaken as part of the event. The status
     * or result of the action should be detailed in the status field.</p>
     */
    public static final Resource Action = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Action");
    /**
     * <p>Network source (CEE:src) or destination (CEE:dst)</p>
     */
    public static final Resource Address = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Address");
    /**
     * <p>Application (CEE:app)</p>
     */
    public static final Resource App = M_MODEL.createResource("https://w3id.org/sepses/ns/log#App");
    /**
     * <p>The class to represent a physical entity/machine that is connected to a computer
     * network (e.g., Server, Client, and Firewall)</p>
     */
    public static final Resource Device = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Device");
    /**
     * <p>The environment or domain of the event. Typical event domains include network
     * (net), operating system (os), and application (app).</p>
     */
    public static final Resource Domain = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Domain");
    /**
     * <p>A representation of a single logline in a log file.</p>
     */
    public static final Resource Event = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Event");
    /**
     * <p>File information (CEE:file)</p>
     */
    public static final Resource File = M_MODEL.createResource("https://w3id.org/sepses/ns/log#File");
    /**
     * <p>The format used to represent loglines for a certain type of log source, e.g.,
     * unix format that is used in Ubuntu's Kernel, Auth, and System log files.</p>
     */
    public static final Resource Format = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Format");
    /**
     * <p>Class to represent Host, which is an (incomplete) address information - in
     * case that there is no clear relation between Host, IP, and Port available</p>
     */
    public static final Resource Host = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Host");
    /**
     * <p>IPv4 or IPv6 address of the event source</p>
     */
    public static final Resource IP = M_MODEL.createResource("https://w3id.org/sepses/ns/log#IP");
    /**
     * <p>IPv4 address of the event source (CEE:ipv4)</p>
     */
    public static final Resource IPv4 = M_MODEL.createResource("https://w3id.org/sepses/ns/log#IPv4");
    /**
     * <p>IPv6 address of the event source (CEE:ipv6)</p>
     */
    public static final Resource IPv6 = M_MODEL.createResource("https://w3id.org/sepses/ns/log#IPv6");
    /**
     * <p>The type of object that is targeted or otherwise affected by the event</p>
     */
    public static final Resource Object = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Object");
    /**
     * <p>The superclass of various classes that represent field dictionary items. Most
     * of them are from CEE standard, while several classes are added (e.g., URL).</p>
     */
    public static final Resource Parameter = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Parameter");
    /**
     * <p>Class to represent Port, which is an (incomplete) address information - in
     * case that there is no clear relation between Host, IP, and Port available</p>
     */
    public static final Resource Port = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Port");
    /**
     * <p>Process (CEE:proc)</p>
     */
    public static final Resource Proc = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Proc");
    /**
     * <p>The service the event involves. The service field value provides context to
     * the event action or more precision to the event domain.</p>
     */
    public static final Resource Service = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Service");
    /**
     * <p>The class represent a single log source. It may represent an aggregation of
     * logs from different applications (e.g., SysLog) or aggregation of several
     * log files from different devices. An instance of this class, however, should
     * only represent log data from a single source type (e.g., Syslog), so it can
     * be processed consistently.</p>
     */
    public static final Resource Source = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Source");
    /**
     * <p>The type of a log source, e.g., apache-access, kernel, syslog, audit, etc.</p>
     */
    public static final Resource SourceType = M_MODEL.createResource("https://w3id.org/sepses/ns/log#SourceType");
    /**
     * <p>The end result or status of the event action identified by the action field.</p>
     */
    public static final Resource Status = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Status");
    /**
     * <p>The type of object that initiated or started the event action identified by
     * the action field.</p>
     */
    public static final Resource Subject = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Subject");
    /**
     * <p>Syslog compatibility (CEE:syslog)</p>
     */
    public static final Resource Syslog = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Syslog");
    /**
     * <p>This class represent a generic annotation class that can be attached to an
     * Event for Event classification.</p>
     */
    public static final Resource Tag = M_MODEL.createResource("https://w3id.org/sepses/ns/log#Tag");
    public static final Resource URL = M_MODEL.createResource("https://w3id.org/sepses/ns/log#URL");
    /**
     * <p>User account (CEE:user)</p>
     */
    public static final Resource User = M_MODEL.createResource("https://w3id.org/sepses/ns/log#User");
    public static final Resource app = M_MODEL.createResource("https://w3id.org/sepses/id/log/app");
    public static final Resource device = M_MODEL.createResource("https://w3id.org/sepses/id/log/device");
    /**
     * <p>The event is occurs within or is associated with the network</p>
     */
    public static final Resource net = M_MODEL.createResource("https://w3id.org/sepses/id/log/net");
    public static final Resource os = M_MODEL.createResource("https://w3id.org/sepses/id/log/os");

    /**
     * <p>The namespace of the vocabulary as a string</p>
     *
     * @return namespace as String
     * @see #NS
     */
    public static String getURI() {
        return NS;
    }

}
